Repository nimblehq/nimble-survey-web, pull requests merged in 2023-08, with the labels that each got.

#106 [#105] Fix: Unable to find latest point release version for 115.0.5790
  Gemfile
  Gemfile.lock
Labels: type : bug

#108 [#107] Update the purge CSS configuration
  tailwind.config.js
Labels: type : chore

#104 Setup Mock Server with Prism
  .github/workflows/mock_deploy.yml
  Dockerfile.mock
  docs/openapi/openapi.yml
  fly.toml
Labels: type : chore

#111 [#110] Fix: session not created: This version of ChromeDriver only supports Chrome version 114
  Gemfile.lock
Labels: type : bug

#109 Release - 2.6.0
  .github/workflows/mock_deploy.yml
  Dockerfile.mock
  Gemfile
  Gemfile.lock
  docs/openapi/openapi.yml
  fly.toml
  tailwind.config.js
Labels: type : release
